server:
  port: 8080

spring:
  application:
    name: mall-tiny
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB      # 单个文件最大大小
      max-request-size: 200MB   # 单次请求最大大小（多个文件时）
#  main:
#    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# knife4j的增强配置，不需要增加此配置也可以正常使用
knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: mall-tiny
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时

secure:
  ignored:
    urls: #安全路径白名单
      - /doc.html
      - /webjars/**
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
